repos:
  - repo: local
    hooks:
      - id: infrastructure-lint
        name: Infrastructure Lint
        entry: ./scripts/pre-commit-lint.sh
        language: system
        files: \.(tf|tf\.json|sh|groovy)$
        pass_filenames: false
        always_run: true