name: development
description: Development environment for testing and development

# Protection rules for development
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
    dismiss_stale_reviews: true
  - type: wait_timer
    wait_timer: 0  # No wait time for dev

# Environment variables
environment_variables:
  ENVIRONMENT: dev
  AWS_REGION: us-east-2
  INSTANCE_TYPE: t3.medium
  ALLOWED_CIDR: 0.0.0.0/0  # Open for development

# Secrets (configured in GitHub repository settings)
secrets:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - SSH_PRIVATE_KEY
