name: production
description: Production environment for live workloads

# Protection rules for production
protection_rules:
  - type: required_reviewers
    required_reviewers: 3
    dismiss_stale_reviews: true
  - type: wait_timer
    wait_timer: 10  # 10 minute wait time
  - type: required_status_checks
    required_status_checks:
      - lint-and-validate
      - deploy-dev  # Must pass dev deployment first

# Environment variables
environment_variables:
  ENVIRONMENT: prod
  AWS_REGION: us-east-2
  INSTANCE_TYPE: t3.xlarge
  ALLOWED_CIDR: 173.63.251.175/32  # Restrict to specific IP

# Secrets (configured in GitHub repository settings)
secrets:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - SSH_PRIVATE_KEY
