name: staging
description: Staging environment for pre-production testing

# Protection rules for staging
protection_rules:
  - type: required_reviewers
    required_reviewers: 2
    dismiss_stale_reviews: true
  - type: wait_timer
    wait_timer: 5  # 5 minute wait time

# Environment variables
environment_variables:
  ENVIRONMENT: stage
  AWS_REGION: us-east-2
  INSTANCE_TYPE: t3.large
  ALLOWED_CIDR: 0.0.0.0/0  # Open for testing

# Secrets (configured in GitHub repository settings)
secrets:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - SSH_PRIVATE_KEY
